### ISSUE TITLE
add Firebase?

### ISSUE THREAD

**Issue by aelam** [d-date/google-mlkit-swiftpm#11]
They share a lot of dependencies, 
Currently, we are using both Firebase and GoogleMLKit. it would be difficult without Firebase support here

Do you have any ideas?

**Comment by d-date** [comment]
@aelam Of course considered about Firebase. See https://github.com/d-date/google-mlkit-swiftpm/blob/main/Example/Package/Package.swift

**Comment by d-date** [comment]
@aelam As you can see my Package.swift, common dependencies are come from SwiftPM.
https://github.com/d-date/google-mlkit-swiftpm/blob/main/Package.swift

My article might be help you (Sorry about written in Japanese)
https://zenn.dev/d_date/articles/cd4ce3b2b5c29d

**Comment by aelam** [comment]
thank you! it looks great
thanks for your hard work

BTW maybe change the package name to GoogleMLKit should be OK? without swifpm suffix

**Comment by d-date** [comment]
@aelam It's OK but have no effect for everywhere. If you want, it's welcome to PR.
